CREATE DATABASE SAI_GON_XUA
GO
USE SAI_GON_XUA
----------------------------ADMIN
CREATE TABLE ADMIN
(
	ID INT NOT NULL,
	NAME NVARCHAR(250) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	AVATAR TEXT NULL,
	EMAIL VARCHAR(100) NULL,
	PHONE VARCHAR(10) NULL,
	STATUS BIT NOT NULL,
	PRIMARY KEY (ID)
)
GO

INSERT INTO [dbo].[ADMIN] VALUES(01,N'TRẦN MINH HOÀNG','AK','12345','SINH VIÊN NĂM 2','HOANG123@GMAIL.COM','0978012345','1 ')
INSERT INTO [dbo].[ADMIN] VALUES(02,N'TRẦN MINH QUÂN','QUÂN123','44444','SINH VIÊN NĂM 3','QUAN123@GMAIL.COM','0986346257','1 ')
INSERT INTO [dbo].[ADMIN] VALUES(03,N'HOÀNG THÙY DUNG','DUNG112','55555','SINH VIÊN NĂM 3','DUNG112@GMAIL.COM','0987935362','0 ')
INSERT INTO [dbo].[ADMIN] VALUES(04,N'ĐẶNG THANH NHÀN','NHÀN999','33333','SINH VIÊN NĂM 3','NHAN999@GMAIL.COM','0167469379','1 ')
INSERT INTO [dbo].[ADMIN] VALUES(05,N'LÊ MỸ NGỌC','NGOC123','222234','SINH VIÊN NĂM 2','NGOC123@GMAIL.COM','0168364278','0 ')

----------------------------USERS
CREATE TABLE USERS
(
	ID INT NOT NULL,
	NAME NVARCHAR(250) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	AVATAR TEXT NULL,
	EMAIL VARCHAR(100) NULL,
	PHONE VARCHAR(10) NULL,
	STATUS BIT NOT NULL,
	PRIMARY KEY (ID)
)
GO

INSERT INTO [dbo].[USERS] VALUES(001,'AN','AN123','9898','GIÁO VIÊN CẤP 3','ANNGUYEN@GMAIL.COM','0987654321','1')
INSERT INTO [dbo].[USERS] VALUES(002,'HẬU','HAU097','1234567','NHÂN VIÊN VĂN PHÒNG','HAUNGUYEN@GMAIL.COM','0123456789','0')
INSERT INTO [dbo].[USERS] VALUES(003,N'NGÂN','NGÂNHOANG','00000000','GIÁO VIÊN CẤP 2','NGANHOANG@GMAIL.COM','0973645536','1')
INSERT INTO [dbo].[USERS] VALUES(004,N'HÙNG','HUNGDO','11111','BÁC SĨ BỆNH VIỆN HOA LỆ','HUNGDO@GMAIL.COM','0283648586','1')
INSERT INTO [dbo].[USERS] VALUES(005,N'MỸ','ANMY','98765', 'GIẢNG VIÊN TRƯỜNG ĐH VĂN LANG','ANMY@GMAIL.COM','0238477746','1')
----------------------CATALOG_PRODUCT
CREATE TABLE CATALOG_PRODUCT
(
	ID INT NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
)
GO

INSERT INTO [dbo].[CATALOG_PRODUCT] VALUES(1,N'TRÀ')
INSERT INTO [dbo].[CATALOG_PRODUCT] VALUES(2,N'TRÀ SỮA')
INSERT INTO [dbo].[CATALOG_PRODUCT] VALUES(3,N'NƯỚC ÉP')
INSERT INTO [dbo].[CATALOG_PRODUCT] VALUES(4,N'BÁNH NGỌT')
INSERT INTO [dbo].[CATALOG_PRODUCT] VALUES(5,N'ĂN VẶT')
-----------------------------PRODUCT
CREATE TABLE PRODUCT
(
	ID INT NOT NULL,
	NAME NVARCHAR NOT NULL,
	CATALOG_ID INT NOT NULL,
	PRICE DECIMAL(15,3) NOT NULL,
	STATUS_PRODUCT BIT NOT NULL,
	PRODUCT_DISPLAY BIT NULL,
	QTY_PRODUCT_ INT NOT NULL,
	DESCRIPTION NVARCHAR(MAX) NOT NULL,
	CREATED DATE NOT NULL,
	PRIMARY KEY (ID)
)
GO

INSERT INTO [dbo].[PRODUCT] VALUES(1,N'TRÀ ĐÀO',1,'15.000','1','0',2,'NGỌT 50','2020-10-1')
INSERT INTO [dbo].[PRODUCT] VALUES(2,N'TRÀ SỮA Ô LONG',2,'20.0000','1','0',2,'NGỌT 50 ĐÁ 50','2020-10-12')
INSERT INTO [dbo].[PRODUCT] VALUES(3,N'NƯỚC ÉP DỨA',3,'25.000','1','0',2,'ÍT ĐÁ','2020-7-1')
INSERT INTO [dbo].[PRODUCT] VALUES(4,N'BÁNH TRÁNG CUỐN',5,'10.000','1','0',2,'SỐT BƠ','2020-3-11')
INSERT INTO [dbo].[PRODUCT] VALUES(5,N'BÔNG LAN TRỨNG MUỐI',4,'20.000','1','0',2,'2 TRỨNG MUỐI','2020-10-1')

ALTER TABLE [dbo].[PRODUCT]
ADD CONSTRAINT DF_PRICE_GIASANPHAM
DEFAULT 0.0000 FOR PRICE

ALTER TABLE [dbo].[PRODUCT]
ADD CONSTRAINT DF_STATUS_ST
DEFAULT 1 FOR STATUS_PRODUCT

ALTER TABLE [dbo].[PRODUCT]
ADD CONSTRAINT DF_DISPLAY_DS
DEFAULT 0 FOR PRODUCT_DISPLAY

ALTER TABLE [dbo].[PRODUCT]
ADD CONSTRAINT DF_QTY
DEFAULT 0 FOR [QTY_PRODUCT_]

ALTER TABLE [dbo].[PRODUCT]
ADD CONSTRAINT FK_CATALOG_ID
FOREIGN KEY([CATALOG_ID]) REFERENCES [dbo].[CATALOG_BLOG]([ID])
-------------------------ORTHERBILL
CREATE TABLE ORDER_BILL
(
	ID	INT NOT NULL,
	USER_NAME	NVARCHAR(250) NOT NULL,
	USER_PHONE	VARCHAR(10) NOT NULL,
	USER_EMAIL	VARCHAR(100) NOT NULL,
	RECIVER_NAME	DECIMAL(15,4) NOT NULL,
	RECIEVER_PHONE	NVARCHAR(100) NOT NULL,
	RECIVER_FLAT	NVARCHAR(100) NOT NULL,
	WARD_ID	INT NOT NULL,
	DISTRICT_ID INT NOT NULL,
	CITY_ID	INT NOT NULL,
	MESSAGE	NVARCHAR(300) NOT NULL,
	PAYMENT	VARCHAR(100) NOT NULL,
	PAYMENT_STATUS	BIT NOT NULL,
	DELIVERY_STATUS_ID	CHAR(10) NOT NULL,
	DAY_CREATED	DATE NOT NULL,
	PRIMARY KEY(ID)
)
GO

INSERT INTO [dbo].[ORDER_BILL] VALUES(1,'AN','0987654321','ANNGUYEN@GMAIL.COM','15','23A',N'TRẦN HƯNG ĐẠO',2,2,2,N'ÍT ĐÁ','MOMO','0','H','2020-10-01')

ALTER TABLE [dbo].[ORDER_BILL]
ADD CONSTRAINT  DF_PAYMENT_ST
DEFAULT 0 FOR [PAYMENT_STATUS]

ALTER TABLE [dbo].[ORDER_BILL]
ADD CONSTRAINT  DF_DELIVERYT_ST
DEFAULT 'H' FOR [DELIVERY_STATUS_ID]
--************************FK

ALTER TABLE [dbo].[ORDER_BILL]
ADD CONSTRAINT  FK_WARD_ID5
FOREIGN KEY(WARD_ID) REFERENCES [dbo].[WARD]([ID])

ALTER TABLE [dbo].[ORDER_BILL]
ADD CONSTRAINT  FK_DISTRICT
FOREIGN KEY(DISTRICT_ID) REFERENCES [dbo].[DISTRICT]([ID])

ALTER TABLE [dbo].[ORDER_BILL]
ADD CONSTRAINT  FK_CITY
FOREIGN KEY(CITY_ID) REFERENCES [dbo].[CITY]([ID])

---------------------------ORDER_DETAIL
CREATE TABLE ORDER_DETAIL
(
	ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	QTY INT NOT NULL,
	AMOUNT DECIMAL(15,4) NOT NULL DEFAULT 0.0000,
	PRIMARY KEY(ID)
)
GO

ALTER TABLE[dbo].[ORDER_DETAIL]
ADD CONSTRAINT DF_ORDER_DL
DEFAULT 0 FOR [QTY]

ALTER TABLE [dbo].[ORDER_DETAIL]
ADD CONSTRAINT FK_PRODUCT
FOREIGN KEY(PRODUCT_ID) REFERENCES [dbo].[PRODUCT]([ID])

-----------------------CATALOG_BLOG
CREATE TABLE CATALOG_BLOG
(
	ID INT NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	PARENT_ID INT NOT NULL DEFAULT 0,
	SORT_ORTHER TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY(ID)
)
GO
------------------------------BLOG
CREATE TABLE BLOG
(
	ID INT NOT NULL,
	CATALOG_ID INT NOT NULL,
	TITLE NVARCHAR(200) NOT NULL,
	CONTENT TEXT NOT NULL,
	IMAGE_LIST TEXT NOT NULL,
	CREATED DATE NOT NULL,
	PRIMARY KEY(ID)
)
GO
ALTER TABLE [dbo].[BLOG]
ADD CONSTRAINT  FK_CATALOG_ID_BLOG
FOREIGN KEY(CATALOG_ID) REFERENCES[dbo].[CATALOG_BLOG] ([ID])

-------------------SATUS_DELIVERY
CREATE TABLE STATUS_DELIVERY
(
	ID CHAR(10) NOT NULL,
	NAME_STATUS NVARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
)
GO
-------------------------WARD
CREATE TABLE WARD
(
	ID INT NOT NULL,
	NAME_WARD NVARCHAR(50) NOT NULL,
	PREFIX NVARCHAR(20) NOT NULL,
	CITY_ID INT NOT NULL,
	DISTRICT_ID INT NOT NULL,
	PRIMARY KEY(ID)
)
GO
--************************FK
ALTER TABLE [dbo].[WARD]
ADD CONSTRAINT  FK_CITY_ID2
FOREIGN KEY(CITY_ID) REFERENCES [dbo].[CITY]([ID])

ALTER TABLE [dbo].[WARD]
ADD CONSTRAINT  FK_DI_ID2
FOREIGN KEY(DISTRICT_ID) REFERENCES [dbo].[DISTRICT]([ID])


-------------------------------DISTRICT
CREATE TABLE DISTRICT
(
	ID INT NOT NULL,
	NAME_DISTRICT NVARCHAR(100) NOT NULL,
	PREFIX NVARCHAR(20) NOT NULL,
	CITY_ID INT NOT NULL,
	PRIMARY KEY(ID)
)
GO
--*********************FK
ALTER TABLE [dbo].[DISTRICT]
ADD CONSTRAINT  FK_CITY_ID3
FOREIGN KEY(CITY_ID) REFERENCES [dbo].[CITY]([ID])
-----------------------------CITY
CREATE TABLE CITY
(
	ID INT NOT NULL,
	NAME_CITY NVARCHAR(50) NOT NULL,
	CODE NVARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
)
GO

SELECT * FROM [dbo].[ADMIN]
SELECT * FROM[dbo].[USERS]
SELECT * FROM[dbo].[BLOG]
SELECT * FROM[dbo].[CATALOG_BLOG]
SELECT * FROM[dbo].[CATALOG_PRODUCT]
SELECT * FROM[dbo].[PRODUCT]
SELECT * FROM[dbo].[CITY]
SELECT * FROM[dbo].[WARD]
SELECT * FROM[dbo].[DISTRICT]
SELECT * FROM[dbo].[ORDER_BILL]
SELECT * FROM[dbo].[ORDER_DETAIL]
SELECT * FROM[dbo].[STATUS_DELIVERY]


